replicaCount: 1

image:
  repository: 092203534677.dkr.ecr.eu-west-2.amazonaws.com/flask-devops-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP  
  port: 80         
  targetPort: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}