replicaCount: 1

image:
  repository: 092203534677.dkr.ecr.eu-west-2.amazonaws.com/flask-devops-app
  tag: "staging"
  pullPolicy: Always

service:
  type: ClusterIP  
  port: 80         
  targetPort: 5000

# Staging environment with lower resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Staging specific configurations
nameOverride: "devops-practice-staging"
fullnameOverride: "devops-practice-staging"