replicaCount: 1

image:
  repository: 092203534677.dkr.ecr.eu-west-2.amazonaws.com/flask-devops-app
  tag: "b5c8992"
  pullPolicy: Always

service:
  type: NodePort  
  port: 80         
  targetPort: 5000 

ingress:
  enabled: true
  host: flask.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
