name: Build and Deploy to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_TAG=${SHORT_SHA}
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ./app/backend
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Update Helm values.yaml with new image tag
      run: |
        sed -i "s/tag: .*/tag: \"$SHORT_SHA\"/" helm/myapp/values.yaml

    - name: Commit and push updated values.yaml
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add helm/myapp/values.yaml
        git commit -m "Update image tag to $SHORT_SHA"
        git push
